services:
  app:
    build:
      context: ./homeOwner-api
      dockerfile: ./Dockerfile
    container_name: laravel_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./homeOwner-api:/var/www/html
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build: ./homeOwner-ui
    container_name: vue-frontend
    volumes:
      - ./homeOwner-ui:/app
      - /app/node_modules  # Prevents overwriting node_modules
    ports:
      - "5173:5173"  # Vite's default hot reload port
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enables file change detection inside Docker
    command: npm run dev

networks:
  app_network:
    driver: bridge
